# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - elasticsearch Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class ElasticsearchV100(UModelCoreObject):
    """elasticsearch class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # ElasticSearch 的核心配置部分，定义实例的连接和索引参数。
    spec: Optional['ElasticsearchV100Spec'] = None

    def get_kind(self) -> str:
        return 'elasticsearch'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class ElasticsearchV100Spec:
    """ElasticSearch 的核心配置部分，定义实例的连接和索引参数。"""
    # ElasticSearch 实例的访问地址（URL）。
    endpoint: Optional[str] = None
    # ElasticSearch 索引名称。
    index: Optional[str] = None
    # ElasticSearch 的版本号（如 7.x、8.x）。
    version: Optional[str] = None
    # ElasticSearch 的额外配置信息，以键值对形式存储。
    properties: Optional[Dict[str, str]] = None
    # 用于表示该 ElasticSearch 存储的标签。
    tags: Optional[Dict[str, str]] = None
