# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - mysql Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class MysqlV100(UModelCoreObject):
    """mysql class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # MySQL 的核心配置部分，定义数据库实例的连接和查询参数。
    spec: Optional['MysqlV100Spec'] = None

    def get_kind(self) -> str:
        return 'mysql'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class MysqlV100Spec:
    """MySQL 的核心配置部分，定义数据库实例的连接和查询参数。"""
    # MySQL 实例的访问地址（host:port）。
    endpoint: Optional[str] = None
    # MySQL 数据库名称。
    database: Optional[str] = None
    # MySQL 表名称。
    table: Optional[str] = None
    # SQL 查询语句，用于从 MySQL 中提取数据。
    sql: Optional[str] = None
    # MySQL 的额外配置信息，以键值对形式存储。
    properties: Optional[Dict[str, str]] = None
    # 用于表示该 MySQL 存储的标签。
    tags: Optional[Dict[str, str]] = None
