# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - prometheus Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class PrometheusV100(UModelCoreObject):
    """prometheus class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # Prometheus 的核心配置部分，定义监控实例的连接和查询参数。
    spec: Optional['PrometheusV100Spec'] = None

    def get_kind(self) -> str:
        return 'prometheus'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class PrometheusV100Spec:
    """Prometheus 的核心配置部分，定义监控实例的连接和查询参数。"""
    # Prometheus 实例的访问地址（URL）。
    endpoint: Optional[str] = None
    # Prometheus 的额外配置信息，以键值对形式存储。
    properties: Optional[Dict[str, str]] = None
    # 用于表示该 Prometheus 存储的标签。
    tags: Optional[Dict[str, str]] = None
