// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// ElasticsearchV100 represents elasticsearch
type ElasticsearchV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec ElasticSearch 的核心配置部分，定义实例的连接和索引参数。
	Spec *ElasticsearchV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证ElasticsearchV100是否符合schema定义
func (s *ElasticsearchV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ElasticsearchV100的类型标识
func (s *ElasticsearchV100) GetKind() string {
	return "elasticsearch"
}

// GetSchema 获取ElasticsearchV100的Schema信息
func (s *ElasticsearchV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取ElasticsearchV100的Metadata信息
func (s *ElasticsearchV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// ElasticsearchV100Spec ElasticSearch 的核心配置部分，定义实例的连接和索引参数。
type ElasticsearchV100Spec struct {
	// Endpoint ElasticSearch 实例的访问地址（URL）。
	Endpoint string `json:"endpoint" yaml:"endpoint"`
	// Index ElasticSearch 索引名称。
	Index string `json:"index" yaml:"index"`
	// Version ElasticSearch 的版本号（如 7.x、8.x）。
	Version string `json:"version,omitempty" yaml:"version,omitempty"`
	// Properties ElasticSearch 的额外配置信息，以键值对形式存储。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 用于表示该 ElasticSearch 存储的标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证ElasticsearchV100Spec是否符合schema定义
func (s *ElasticsearchV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
