// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// MysqlV100 represents mysql
type MysqlV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec MySQL 的核心配置部分，定义数据库实例的连接和查询参数。
	Spec *MysqlV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证MysqlV100是否符合schema定义
func (s *MysqlV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取MysqlV100的类型标识
func (s *MysqlV100) GetKind() string {
	return "mysql"
}

// GetSchema 获取MysqlV100的Schema信息
func (s *MysqlV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取MysqlV100的Metadata信息
func (s *MysqlV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// MysqlV100Spec MySQL 的核心配置部分，定义数据库实例的连接和查询参数。
type MysqlV100Spec struct {
	// Endpoint MySQL 实例的访问地址（host:port）。
	Endpoint string `json:"endpoint" yaml:"endpoint"`
	// Database MySQL 数据库名称。
	Database string `json:"database" yaml:"database"`
	// Table MySQL 表名称。
	Table string `json:"table,omitempty" yaml:"table,omitempty"`
	// Sql SQL 查询语句，用于从 MySQL 中提取数据。
	Sql string `json:"sql,omitempty" yaml:"sql,omitempty"`
	// Properties MySQL 的额外配置信息，以键值对形式存储。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 用于表示该 MySQL 存储的标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证MysqlV100Spec是否符合schema定义
func (s *MysqlV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
