// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// PrometheusV100 represents prometheus
type PrometheusV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec Prometheus 的核心配置部分，定义监控实例的连接和查询参数。
	Spec *PrometheusV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证PrometheusV100是否符合schema定义
func (s *PrometheusV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取PrometheusV100的类型标识
func (s *PrometheusV100) GetKind() string {
	return "prometheus"
}

// GetSchema 获取PrometheusV100的Schema信息
func (s *PrometheusV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取PrometheusV100的Metadata信息
func (s *PrometheusV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// PrometheusV100Spec Prometheus 的核心配置部分，定义监控实例的连接和查询参数。
type PrometheusV100Spec struct {
	// Endpoint Prometheus 实例的访问地址（URL）。
	Endpoint string `json:"endpoint" yaml:"endpoint"`
	// Properties Prometheus 的额外配置信息，以键值对形式存储。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 用于表示该 Prometheus 存储的标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证PrometheusV100Spec是否符合schema定义
func (s *PrometheusV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
